# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pull_and_push:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: docker login 
        run: echo ${{ secrets.PASSWORD }}  | docker login --username=${{ secrets.USERNAME }} --password-stdin registry.cn-hangzhou.aliyuncs.com


      - name: docker pull and push
        run: |
          for i in $(cat list.txt); 
          do 
            docker pull $i  ;
            docker tag $i registry.cn-hangzhou.aliyuncs.com/cachei/${i##*/} ;
            docker push registry.cn-hangzhou.aliyuncs.com/cachei/${i##*/}  ;
            echo "$i has been pushed to registry.cn-hangzhou.aliyuncs.com/cachei." ;  
          done
      - name: docker logout 
        run: docker logout registry.cn-hangzhou.aliyuncs.com
      - name: Generate a pull script
        run: |
          echo 'echo 密码  | docker login --username=用户名 --password-stdin registry.cn-hangzhou.aliyuncs.com'
          for i in $(cat list.txt); 
          do
            echo "docker pull registry.cn-hangzhou.aliyuncs.com/cachei/${i##*/} "
            echo "docker tag registry.cn-hangzhou.aliyuncs.com/cachei/${i##*/} $i"
            echo "docker rmi registry.cn-hangzhou.aliyuncs.com/cachei/${i##*/}"
          done
          
          echo 'docker logout registry.cn-hangzhou.aliyuncs.com'
      
      
